# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nship < Formula
  desc "A flexible and efficient deployment automation tool for streamlining execution of deployment jobs across multiple targets"
  homepage "https://nship.dev"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nickalie/nship/releases/download/v0.2.1/nship_Darwin_x86_64.tar.gz"
      sha256 "a9c5b60e84059dd8e88cd94abf4ce04484da770cb1a3ea1763363b8b853b7fc0"

      def install
        bin.install "nship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nickalie/nship/releases/download/v0.2.1/nship_Darwin_arm64.tar.gz"
      sha256 "0477deb04c66859183cd5bbd99d20bba19e65e1780af11fb5e5b1dfc4ef6d988"

      def install
        bin.install "nship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nickalie/nship/releases/download/v0.2.1/nship_Linux_x86_64.tar.gz"
        sha256 "2bfbcfd774b871800d5d1ced96d580b543151b0602cb40a3a7b370c19935cf0c"

        def install
          bin.install "nship"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nickalie/nship/releases/download/v0.2.1/nship_Linux_arm64.tar.gz"
        sha256 "78e7f11d4959ec4b994785f0711315e7b1ed9ca3b3912c5235b07af1e5864392"

        def install
          bin.install "nship"
        end
      end
    end
  end

  test do
    system "#{bin}/program --version"
  end
end
