# This file was generated by GoReleaser. DO NOT EDIT.
cask "nclaw" do
  name "nclaw"
  desc "Lightweight, container-first AI assistant powered by Claude Code, accessible through Telegram"
  homepage "https://github.com/nickalie/nclaw"
  version "0.8.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nclaw"

  on_macos do
    on_intel do
      url "https://github.com/nickalie/nclaw/releases/download/v#{version}/nclaw_#{version}_darwin_amd64.tar.gz"
      sha256 "835aaa85e291cc9ad4bc4eb561ed48c8656da5e27b01df42ac45530e29b35787"
    end
    on_arm do
      url "https://github.com/nickalie/nclaw/releases/download/v#{version}/nclaw_#{version}_darwin_arm64.tar.gz"
      sha256 "f6797543a4b9ff2cee24dfd296bbc7ca32745d98345e6a59db37adc3102084ae"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nickalie/nclaw/releases/download/v#{version}/nclaw_#{version}_linux_amd64.tar.gz"
      sha256 "8dc59abedec3e2d623c3af2cd8d8772053c210670d35ac7e39a5d70abf36cfbd"
    end
    on_arm do
      url "https://github.com/nickalie/nclaw/releases/download/v#{version}/nclaw_#{version}_linux_arm64.tar.gz"
      sha256 "95fd29080fd3193fe2ddfff831a0385e26a7f0d7b731df4faf8589795ea55103"
    end
  end

  # No zap stanza required
end
