# This file was generated by GoReleaser. DO NOT EDIT.
cask "nclaw" do
  name "nclaw"
  desc "Lightweight, container-first AI assistant powered by Claude Code, accessible through Telegram"
  homepage "https://github.com/nickalie/nclaw"
  version "0.15.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nclaw"

  on_macos do
    on_intel do
      url "https://github.com/nickalie/nclaw/releases/download/v#{version}/nclaw_#{version}_darwin_amd64.tar.gz"
      sha256 "213a18e6676935dee8c0385beab9273615a31a7bf4601fe55305d5b4556960d9"
    end
    on_arm do
      url "https://github.com/nickalie/nclaw/releases/download/v#{version}/nclaw_#{version}_darwin_arm64.tar.gz"
      sha256 "74d1ef4e56839e53164b6e5c8061baf941b82d979465e39eee932bb507222094"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nickalie/nclaw/releases/download/v#{version}/nclaw_#{version}_linux_amd64.tar.gz"
      sha256 "9b38db38365d22bf244dd2e2f7a7c9b2244978995b1f8760455d652585c5b4d2"
    end
    on_arm do
      url "https://github.com/nickalie/nclaw/releases/download/v#{version}/nclaw_#{version}_linux_arm64.tar.gz"
      sha256 "e64eaec98efeb8104e2ed3c777b553384d61114b6de95c68c84cc4049fc71d7d"
    end
  end

  # No zap stanza required
end
